#!/usr/bin/env bash
# Production Apigee Hybrid overrides.yaml (Kubernetes Secrets — one secret per service account).
# Secret names match Google's v1.16 production flow and lib/hybrid-checklist.sh checks.
# shellcheck shell=bash

DOC_INSTALL_OVERRIDES_DEFAULT="https://docs.cloud.google.com/apigee/docs/hybrid/v1.16/install-create-overrides"

# Emit overrides.yaml to stdout (production: distinct serviceAccountRef per component).
# Args:
#   1 instance_id  2 namespace  3 project_id  4 analytics_region
#   5 cluster_name  6 cluster_region  7 org_name
#   8 environment_name  9 env_group
#   10 control_plane_location (empty = omit contractProvider)
#   11 ingress_name
#   12 ssl_cert_rel  13 ssl_key_rel (paths relative to apigee-virtualhost chart)
#   14 svc_annotation_key  15 svc_annotation_value (both nonempty or annotations omitted)
#   16 runtime_image_tag
#   17 include_large_payload (1 or 0)
# connectAgent uses the mart service account (Google production samples).
# mintTaskScheduler uses the synchronizer service account.
cshell_hybrid_emit_prod_overrides_secretrefs() {
	local instance_id="$1" namespace="$2" project_id="$3" analytics_region="$4"
	local cluster_name="$5" cluster_region="$6" org_name="$7"
	local environment_name="$8" env_group="$9"
	local control_plane_location="${10}"
	local ingress_name="${11}"
	local ssl_cert_rel="${12}" ssl_key_rel="${13}"
	local svc_key="${14}" svc_val="${15}"
	local runtime_tag="${16}" large="${17}"
	local doc_url="${DOC_INSTALL_OVERRIDES:-${DOC_INSTALL_OVERRIDES_DEFAULT}}"

	{
		printf '%s\n' "# Apigee Hybrid production overrides (Kubernetes Secrets)"
		printf '%s\n' "# Generated by cshell — seven service accounts; see: ${doc_url}"
		printf '%s\n' "instanceID: ${instance_id}"
		printf '%s\n' "namespace: ${namespace} # Usually \"apigee\""
		printf '%s\n' ""
		printf '%s\n' "gcp:"
		printf '%s\n' "  projectID: ${project_id}"
		printf '%s\n' "  region: ${analytics_region}"
		printf '%s\n' ""
		printf '%s\n' "k8sCluster:"
		printf '%s\n' "  name: ${cluster_name}"
		printf '%s\n' "  region: ${cluster_region} # CLUSTER_LOCATION in Google docs"
		printf '%s\n' ""
		printf '%s\n' "org: ${org_name}"
		printf '%s\n' ""
		printf '%s\n' "enhanceProxyLimits: true"
		printf '%s\n' ""
		if [[ -n "${control_plane_location}" ]]; then
			printf '%s\n' "# Data residency control plane"
			printf '%s\n' "contractProvider: https://${control_plane_location}-apigee.googleapis.com"
			printf '%s\n' ""
		else
			printf '%s\n' "# No regional control plane URL: set CONTROL_PLANE_LOCATION for data residency."
			printf '%s\n' ""
		fi
		printf '%s\n' "envs:"
		printf '%s\n' "- name: ${environment_name}"
		printf '%s\n' "  serviceAccountSecretRefs:"
		printf '%s\n' "    synchronizer: apigee-synchronizer-svc-account"
		printf '%s\n' "    runtime: apigee-runtime-svc-account"
		printf '%s\n' ""
		printf '%s\n' "cassandra:"
		printf '%s\n' "  hostNetwork: false"
		printf '%s\n' "  replicaCount: 1"
		printf '%s\n' ""
		printf '%s\n' "ingressGateways:"
		printf '%s\n' "- name: ${ingress_name} # max 17 characters"
		printf '%s\n' "  replicaCountMin: 2"
		printf '%s\n' "  replicaCountMax: 10"
		if [[ -n "${svc_key}" && -n "${svc_val}" ]]; then
			printf '%s\n' "  svcAnnotations:"
			printf '%s\n' "    ${svc_key}: ${svc_val}"
		fi
		printf '%s\n' ""
		printf '%s\n' "virtualhosts:"
		printf '%s\n' "- name: ${env_group}"
		printf '%s\n' "  selector:"
		printf '%s\n' "    app: apigee-ingressgateway"
		printf '%s\n' "    ingress_name: ${ingress_name}"
		printf '%s\n' "  sslCertPath: ${ssl_cert_rel}"
		printf '%s\n' "  sslKeyPath: ${ssl_key_rel}"
		printf '%s\n' ""
		printf '%s\n' "guardrails:"
		printf '%s\n' "  serviceAccountRef: apigee-guardrails-svc-account"
		printf '%s\n' ""
		printf '%s\n' "mart:"
		printf '%s\n' "  serviceAccountRef: apigee-mart-svc-account"
		printf '%s\n' ""
		printf '%s\n' "connectAgent:"
		printf '%s\n' "  serviceAccountRef: apigee-mart-svc-account"
		printf '%s\n' ""
		printf '%s\n' "logger:"
		printf '%s\n' "  enabled: true"
		printf '%s\n' "  serviceAccountRef: apigee-logger-svc-account"
		printf '%s\n' ""
		printf '%s\n' "metrics:"
		printf '%s\n' "  serviceAccountRef: apigee-metrics-svc-account"
		printf '%s\n' ""
		printf '%s\n' "watcher:"
		printf '%s\n' "  serviceAccountRef: apigee-watcher-svc-account"
		printf '%s\n' ""
		printf '%s\n' "runtime:"
		printf '%s\n' "  serviceAccountRef: apigee-runtime-svc-account"
		printf '%s\n' "  image:"
		printf '%s\n' "    url: \"gcr.io/apigee-release/hybrid/apigee-runtime\""
		printf '%s\n' "    tag: \"${runtime_tag}\""
		if [[ "${large}" == "1" ]]; then
			printf '%s\n' "  cwcAppend:"
			printf '%s\n' "    bin_setenv_max_mem: 4096m"
			printf '%s\n' "  resources:"
			printf '%s\n' "    requests:"
			printf '%s\n' "      memory: 4Gi"
			printf '%s\n' "    limits:"
			printf '%s\n' "      memory: 6Gi"
		fi
		printf '%s\n' ""
		printf '%s\n' "mintTaskScheduler:"
		printf '%s\n' "  serviceAccountRef: apigee-synchronizer-svc-account"
	}
}

# Atomic write ${charts_home}/overrides.yaml. Returns 0 on success.
cshell_hybrid_atomic_write_prod_overrides() {
	local charts_home="$1" overwrite="$2"
	shift 2
	[[ -n "${charts_home}" && -d "${charts_home}" ]] || return 1
	local out="${charts_home}/overrides.yaml"
	if [[ -e "${out}" && "${overwrite}" != "1" ]]; then
		return 2
	fi
	local tmp
	tmp="$(mktemp "${TMPDIR:-/tmp}/cshell-hybrid-overrides-prod.XXXXXX")"
	cshell_hybrid_emit_prod_overrides_secretrefs "$@" >"${tmp}"
	mv -f "${tmp}" "${out}"
	return 0
}
